// orbe_sidebars.js


/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  orbeSidebar: [
    {
      type: 'category',
      label: 'Eventos',
      link: { type: 'generated-index', title: 'Eventos'},
      items: [{type: 'autogenerated', dirName: 'orbe/eventos'}],
    },

    {
      type: 'category',
      label: 'Familias y Organizaciones',
      link: { type: 'generated-index', title: 'Familias y Organizaciones'},
      items: [{type: 'autogenerated', dirName: 'orbe/familias'}],
    },

    {
      type: 'category',
      label: 'Lugares',
      link: { type: 'generated-index', title: 'Lugares'},
      items: [{type: 'autogenerated', dirName: 'orbe/lugares'}],
    },

    {
      type: 'category',
      label: 'Personajes',
      link: { type: 'generated-index', title: 'Personajes'},
      items: [{type: 'autogenerated', dirName: 'orbe/personajes'}],
    },

    {
      type: 'category',
      label: 'Otros',
      link: { type: 'generated-index', title: 'Otros'},
      items: [{type: 'autogenerated', dirName: 'orbe/otros'}],
    },

  ],

};

module.exports = sidebars;