/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  orbeSidebar: [
    {
      type: 'category',
      label: 'El Orbe de los Destinos',
      link: { type: 'generated-index', title: 'El Orbe de los Destinos', slug: '/orbe' },
      items: [{ type: 'autogenerated', dirName: 'orbe' }],
    },
  ],
  crsasoSidebar: [
    {
      type: 'category',
      label: 'Crónicas de Sangre y Sombras',
      link: { type: 'generated-index', title: 'Crónicas de Sangre y Sombras', slug: '/CrSaSo' },
      items: [{ type: 'autogenerated', dirName: 'CrSaSo' }],
    },
  ],
};

export default sidebars;
