Ante la falta de pistas concretas en la investigación de [El Cuarto Rojo](El%20Cuarto%20Rojo.md), [Cassian Thorne](Cassian%20Thorne.md) recurrió a [Pollione Tornatore](Pollione%20Tornatore.md) con el objetivo de averiguar la identidad del líder de [La Cruz](La%20Cruz.md). Esta búsqueda los llevó a centrar su atención en la [Catedral de Santa Regina](Catedral%20de%20Santa%20Regina.md), epicentro de actividades sospechosas vinculadas a la organización.

Previo a la operación, [Lucia Sinclair](../Personajes/Lucia%20Sinclair.md) y su equipo realizaron varios días de vigilancia encubierta en los alrededores de la catedral, analizando patrones, rutinas litúrgicas y comportamientos del clero. Durante esta etapa de espionaje, Lucía tuvo su primer contacto directo con [Tamara Dobrescu](Tamara%20Dobrescu.md), también conocida como _Angelina Pollard_, quien intentó persuadirla de unirse a su causa. Lucía, aunque desconcertada por el encuentro, rechazó la oferta.

La infiltración fue posible gracias a una operación conjunta con la [La Comisaría de Nueva Ámsterdam](La%20Comisaría%20de%20Nueva%20Ámsterdam.md), en la que [Dorian Blackwood](Dorian%20Blackwood.md) desempeñó un papel estratégico al reclutar a [Logan Crane](Logan%20Crane.md) como refuerzo. Para completar el plan, se recurrió a [Veronica Black](../Personajes/Veronica%20Black.md), quien diseñó el disfraz y la identidad falsa que permitiría a Lucía acceder al recinto religioso. Esta acción fue concebida bajo la sugerencia de [Archie Woodward](Archie%20Woodward.md), quien, con su conocimiento del mundo oculto y su instinto teatral, propuso contactar con Verónica para garantizar la credibilidad del disfraz.

Durante su estancia encubierta en la catedral, Lucía fue guiada a través de una experiencia psicodélica por [Cecilia Giannotti](Cecilia%20Giannotti.md), durante la cual despertó sus habilidades latentes como bruja. En ese trance espiritual logró conectarse accidentalmente con la versión espectral de Cassian, alertándolo de que algo no marchaba bien en la infiltración.

Desorientada y aún procesando su despertar, Lucía intentó tomar a Cecilia como rehén para forzar a [Marco Giannotti](Marco%20Giannotti.md) a rendirse ante la policía. Sin embargo, Cecilia se liberó mediante un hechizo rápido, y Marco la inmovilizó con una serie de golpes precisos. Lucía resistió, pero fue superada por la fuerza y pericia del cazador. Solo se detuvo cuando Cassian intervino apuntando a Cecilia con su revólver, logrando así desactivar la confrontación.

Tras calmarse los ánimos, se estableció un diálogo entre ambas partes. Marco y Cecilia, reconociendo el potencial de los detectives, los invitaron a integrarse como miembros de [Los Vinculados](Los%20Vinculados.md). Cassian fue reconocido como un cazador nato, mientras que Lucía fue aceptada como bruja, recibiendo como primer obsequio un recetario básico que marcó el inicio formal de su entrenamiento.